### ISSUE TITLE
[ERROR] Runing the docker image

### ISSUE THREAD

**Issue by jerkhouri** [libreoffice-docker/libreoffice-unoserver#3]
Hello, I'm trying to run your image in a classic developer environment, but it seems that I've got an error, see screenshot below.
![image](https://github.com/libreoffice-docker/libreoffice-unoserver/assets/39912632/a8cd8474-36ee-46fb-8d34-c874b28afa59)
I've couldn't find anything about "fonts" in your documentation.

What did I miss ? 

Thanks a lot.

**Comment by socheatsok78** [comment]
This is due to the fact that you are running the nightly built image that is outdated.

You shouldn't the `nightly` image. Please build your own image by create your own repo using the "Use this template" button and add you customization there.
